### ISSUE TITLE
Rest api server failed to start on Kali

### ISSUE THREAD

**Issue by lmcthbe** [infobyte/faraday#272]
Using Kali rolling-update with Faraday 2.7.2, the REST API server failed to start with the error below. couchdb and faraday-server are OK

2018-08-31 13:33:22,911 - faraday.launcher - INFO - Starting Faraday IDE.
2018-08-31 13:33:22,911 - faraday.launcher - INFO - Checking configuration.
2018-08-31 13:33:22,911 - faraday.launcher - INFO - Setting up plugins.
2018-08-31 13:33:22,911 - faraday.launcher - INFO - Removing old plugins folder.
2018-08-31 13:33:22,936 - faraday.launcher - INFO - Setting up ZSH integration.
2018-08-31 13:33:22,936 - faraday.launcher - INFO - Setting up user configuration.
2018-08-31 13:33:22,936 - faraday.launcher - INFO - Copying default configuration from project.
2018-08-31 13:33:22,940 - faraday.launcher - INFO - Setting up icons for GTK interface.
2018-08-31 13:33:22,945 - faraday.launcher - INFO - Setting configuration.
2018-08-31 13:33:23,034 - faraday.launcher - INFO - All done. Opening environment.
2018-08-31 13:33:23,168 - faraday.launcher - INFO - Main application ExceptHook enabled.
2018-08-31 13:33:23,168 - faraday.launcher - INFO - Starting main application.

*              faraday ui is ready              
Make sure you got couchdb up and running.
If couchdb is up, point your browser to: 
[http://127.0.0.1:5985/_ui]

2018-08-31 13:33:23,169 - faraday - INFO - XMLRPC API server configured on ('localhost', 9876)
There was an error while starting Faraday
--------------------------------------------------
Traceback (most recent call last):
  File "/usr/share/python-faraday/model/application.py", line 145, in start
    CONF.getApiRestfulConInfoPort()
  File "/usr/share/python-faraday/apis/rest/api.py", line 67, in startAPIs
    raise Exception("No ports available!")
Exception: No ports available!
--------------------------------------------------

root@kali:~# systemctl status python-faraday
● python-faraday.service - python-faraday Server
   Loaded: loaded (/lib/systemd/system/python-faraday.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-08-31 13:33:02 EDT; 11min ago
 Main PID: 12423 (faraday-server.)
    Tasks: 8 (limit: 4915)
   Memory: 62.7M
   CGroup: /system.slice/python-faraday.service
           └─12423 /usr/bin/python2.7 /usr/share/python-faraday/faraday-server.py

Aug 31 13:33:02 kali systemd[1]: Started python-faraday Server.
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,338 - faraday-server.server.config - INFO - Local faraday-server configuration created at /r
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,441 - faraday-server.server.importer - INFO - Setting up workspace cdx-test
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,494 - faraday-server.server.importer - INFO - Setting up workspace cdx-test-nmap
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,500 - faraday-server.server.importer - INFO - Setting up workspace openvas-test
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,507 - faraday-server.server.importer - INFO - Setting up workspace test
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,515 - faraday-server.server.importer - INFO - Setting up workspace udn-de
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,522 - faraday-server.server.importer - INFO - Setting up workspace udn-prod-nmap
Aug 31 13:33:02 kali faraday-server.py[12423]: 2018-08-31 13:33:02,683 - faraday-server.__main__ - INFO - Faraday Server is ready
Aug 31 13:41:23 kali faraday-server.py[12423]: No handlers could be found for logger "sqlalchemy.pool.NullPool"
root@kali:~# systemctl status couchdb
● couchdb.service - Couchdb service
   Loaded: loaded (/lib/systemd/system/couchdb.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-08-31 13:22:55 EDT; 22min ago
 Main PID: 4931 (beam.smp)
    Tasks: 14 (limit: 4915)
   Memory: 47.0M
   CGroup: /system.slice/couchdb.service
           ├─4931 /usr/lib/erlang/erts-6.3/bin/beam.smp -Bd -K true -A 4 -- -root /usr/lib/erlang -progname erl -- -home /var/lib/couchdb -- -noshell -noinput 
           └─4959 sh -s disksup

Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1747.0>] 127.0.0.1 - - GET /udn-de/udn-de 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1748.0>] 127.0.0.1 - - GET /_all_dbs 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1749.0>] 127.0.0.1 - - GET /cdx-test/cdx-test 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1750.0>] 127.0.0.1 - - GET /cdx-test-nmap/cdx-test-nmap 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1751.0>] 127.0.0.1 - - GET /openvas-test/openvas-test 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1812.0>] 127.0.0.1 - - GET /test/test 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1813.0>] 127.0.0.1 - - GET /udn-de/udn-de 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1814.0>] 127.0.0.1 - - GET /udn-prod-nmap/udn-prod-nmap 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1815.0>] 127.0.0.1 - - GET /udn-de/udn-de 200
Aug 31 13:45:23 kali couchdb[4931]: [info] [<0.1816.0>] 127.0.0.1 - - GET /udn-de 200

2018-08-31 13:35:55,099 - faraday - INFO - Closing Faraday...
root@kali:~# /usr/share/python-faraday/faraday.py -v
Faraday v2.7.2

root@kali:~# netstat -nlp | grep -vi unix
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:5984          0.0.0.0:*               LISTEN      4931/beam.smp       
tcp        0      0 127.0.0.1:5985          0.0.0.0:*               LISTEN      12423/python2.7

**Comment by WinnaZ** [comment]
Would you please send us the result of running:
`netstat -onaput`
Also, we have already released the version 3 of Faraday.
It has a lot of improvements, i invite you to try it out :)

**Comment by lmcthbe** [comment]
root@kali:~# netstat -onaput
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name     Timer
tcp        0      0 127.0.0.1:5984          0.0.0.0:*               LISTEN      2644/beam.smp        off (0.00/0/0)
tcp        0      0 127.0.0.1:5985          0.0.0.0:*               LISTEN      2687/python2.7       off (0.00/0/0)
tcp        0      0 10.152.11.186:54070     172.217.13.110:80       ESTABLISHED 2740/firefox-esr     keepalive (5.48/0/0)
tcp        0      0 127.0.0.1:5985          127.0.0.1:53900         TIME_WAIT   -                    timewait (0.53/0/0)
tcp        0      0 10.152.11.186:37450     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:34208     192.30.253.125:443      ESTABLISHED 2740/firefox-esr     keepalive (508.70/0/0)
tcp        0      0 10.152.11.186:37458     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:55684     52.38.215.55:443        TIME_WAIT   -                    timewait (10.95/0/0)
tcp        0      0 10.152.11.186:37478     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:39730     65.52.1.21:443          ESTABLISHED 2740/firefox-esr     keepalive (0.32/0/0)
tcp        0      0 10.152.11.186:35676     34.215.13.51:443        TIME_WAIT   -                    timewait (9.51/0/0)
tcp        0      0 127.0.0.1:5984          127.0.0.1:60504         ESTABLISHED 2644/beam.smp        off (0.00/0/0)
tcp        0      0 10.152.11.186:37464     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:37476     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:47616     66.130.62.186:80        TIME_WAIT   -                    timewait (59.16/0/0)
tcp        0      0 10.152.11.186:37466     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:34362     54.68.24.18:443         TIME_WAIT   -                    timewait (8.80/0/0)
tcp        0      0 10.152.11.186:39690     172.217.13.110:443      ESTABLISHED 2740/firefox-esr     off (0.00/0/0)
tcp        0      0 10.152.11.186:55998     13.107.18.11:443        ESTABLISHED 2740/firefox-esr     off (0.00/0/0)
tcp        0      0 10.152.11.186:37454     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:38728     50.17.30.248:443        TIME_WAIT   -                    timewait (29.30/0/0)
tcp        0      0 10.152.11.186:37468     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:48620     192.30.253.117:443      TIME_WAIT   -                    timewait (23.67/0/0)
tcp        0      0 10.152.11.186:48984     72.21.91.29:80          ESTABLISHED 2740/firefox-esr     keepalive (0.37/0/0)
tcp        0      0 10.152.11.186:37474     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:48986     72.21.91.29:80          ESTABLISHED 2740/firefox-esr     keepalive (5.49/0/0)
tcp        0      0 127.0.0.1:60504         127.0.0.1:5984          ESTABLISHED 2687/python2.7       off (0.00/0/0)
tcp        0      0 10.152.11.186:42840     52.84.93.43:443         ESTABLISHED 2740/firefox-esr     keepalive (2.40/0/0)
tcp        0      0 10.152.11.186:44998     34.210.48.174:443       ESTABLISHED 2740/firefox-esr     keepalive (0.46/0/0)
tcp        0      0 10.152.11.186:56768     24.200.120.17:80        TIME_WAIT   -                    timewait (54.16/0/0)
tcp        0      0 10.152.11.186:37452     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:37460     151.101.0.133:443       ESTABLISHED 2740/firefox-esr     keepalive (0.57/0/0)
tcp        0      0 10.152.11.186:36494     192.30.253.113:443      TIME_WAIT   -                    timewait (35.27/0/0)
udp        0      0 0.0.0.0:68              0.0.0.0:*                           1127/dhclient        off (0.00/0/0)

I noticed in ~/.faraday/config/user.xml that <api_restful_con_info_port> is set 65535 and when I set it to 9977, it changed back to the previous value when the faraday API server failed to start

**Comment by llazzaro** [comment]
Hi,
Could you send us the error of the server? The log is located at ~/.faraday/logs/faraday-server.log, you should see a trace back with an error if the server returned a 500 error.

Thanks

**Comment by lmcthbe** [comment]
The trace are related before the upgrade to v3
2018-09-05 08:42:27,328 - faraday-server.server.couchdb - DEBUG - Pushing Reports DB into CouchDB
2018-09-05 08:42:27,680 - faraday-server.server.importer - INFO - Setting up workspace cdx-test
2018-09-05 08:42:27,777 - faraday-server.server.importer - INFO - Setting up workspace cdx-test-nmap
2018-09-05 08:42:27,805 - faraday-server.server.importer - INFO - Setting up workspace openvas-test
2018-09-05 08:42:27,827 - faraday-server.server.importer - INFO - Setting up workspace test
2018-09-05 08:42:27,847 - faraday-server.server.importer - INFO - Setting up workspace udn-de
2018-09-05 08:42:27,872 - faraday-server.server.importer - INFO - Setting up workspace udn-prod-nmap
2018-09-05 08:42:28,405 - faraday-server.__main__ - INFO - Faraday Server is ready
2018-09-05 08:42:44,684 - faraday-server.server.web - DEBUG - -> CouchDB: GET /

But I got this backtrace by starting the server manually

 root@kali:/usr/share/python-faraday# ./faraday-server.py -h
Traceback (most recent call last):
  File "./faraday-server.py", line 20, in <module>
    from server.web import app
  File "/usr/share/python-faraday/server/web.py", line 38, in <module>
    app = create_app()  # creates a Flask(__name__) app
  File "/usr/share/python-faraday/server/app.py", line 247, in create_app
    register_blueprints(app)
  File "/usr/share/python-faraday/server/app.py", line 87, in register_blueprints
    app.register_blueprint(handlers_api)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/local/lib/python2.7/dist-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/usr/local/lib/python2.7/dist-packages/flask/blueprints.py", line 128, in wrapper
    func(state)
  File "/usr/local/lib/python2.7/dist-packages/flask/blueprints.py", line 399, in <lambda>
    self.name, code_or_exception, f))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1090, in _register_error_handler
    'It is currently not possible to register a 500 internal ' \
AssertionError: It is currently not possible to register a 500 internal server error on a per-blueprint level.
root@kali:/usr/share/python-faraday# systemctl status python-faraday
● python-faraday.service - python-faraday Server
   Loaded: loaded (/lib/systemd/system/python-faraday.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-09-05 09:18:33 EDT; 29min ago
  Process: 8693 ExecStartPre=/bin/sh -c if ! su postgres -c "psql -lqt" | cut -d \| -f 1 | grep -qw faraday; then cd /usr/share/python-faraday && python manage
 Main PID: 2687 (code=exited, status=0/SUCCESS)

Sep 05 09:18:33 kali sh[8693]:   File "/usr/local/lib/python2.7/dist-packages/flask/blueprints.py", line 399, in <lambda>
Sep 05 09:18:33 kali sh[8693]:     self.name, code_or_exception, f))
Sep 05 09:18:33 kali sh[8693]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 62, in wrapper_func
Sep 05 09:18:33 kali sh[8693]:     return f(self, *args, **kwargs)
Sep 05 09:18:33 kali sh[8693]:   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1090, in _register_error_handler
Sep 05 09:18:33 kali sh[8693]:     'It is currently not possible to register a 500 internal ' \
Sep 05 09:18:33 kali sh[8693]: AssertionError: It is currently not possible to register a 500 internal server error on a per-blueprint level.
Sep 05 09:18:33 kali systemd[1]: python-faraday.service: Control process exited, code=exited status=1
Sep 05 09:18:33 kali systemd[1]: python-faraday.service: Failed with result 'exit-code'.
Sep 05 09:18:33 kali systemd[1]: Failed to start python-faraday Server.

**Comment by llazzaro** [comment]
I think you have some depencies old.
Which is the output of "pip freeze | grep Flask"

Can you try to update the dependencies with:

`pip install -r requirements_server.txt -U`

**Comment by lmcthbe** [comment]
pip freeze | grep Flask
Warning: cannot find svn location for chirp===daily-20180815
Flask==0.10.1
Flask-BabelEx==0.9.3
Flask-Classful==0.14.1
Flask-Login==0.4.1
Flask-Mail==0.9.1
Flask-Principal==0.4.0
Flask-Security==3.0.0
Flask-Session==0.3.1
Flask-SQLAlchemy==2.1
Flask-WTF==0.14.2

With Kali, there is no requirements file for Faraday so I cannot update the dependencies that way

**Comment by llazzaro** [comment]
It seems that your python libraries are old.
make a backup just in case with:
`pip freeze > python_lib_versions.txt
`
Then download the requirements_server.txt file and update using pip:

```
wget https://raw.githubusercontent.com/infobyte/faraday/master/requirements_server.txt
pip install -r requirements_server.txt -U
```

**Comment by lmcthbe** [comment]
It helps but failed on something else

root@kali:/usr/share/python-faraday# systemctl status python-faraday
● python-faraday.service - python-faraday Server
   Loaded: loaded (/lib/systemd/system/python-faraday.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-09-05 13:42:37 EDT; 1min 50s ago
  Process: 11040 ExecStartPre=/bin/sh -c if ! su postgres -c "psql -lqt" | cut -d \| -f 1 | grep -qw faraday; then cd /usr/share/python-faraday && python manag
 Main PID: 2687 (code=exited, status=0/SUCCESS)

Sep 05 13:42:35 kali systemd[1]: Starting python-faraday Server...
Sep 05 13:42:35 kali su[11041]: (to postgres) root on none
Sep 05 13:42:35 kali su[11041]: pam_unix(su:session): session opened for user postgres by (uid=0)
Sep 05 13:42:35 kali su[11041]: pam_unix(su:session): session closed for user postgres
Sep 05 13:42:37 kali sh[11040]: Database section  already found. Do you want to reconfigure database? (yes/no)
Sep 05 13:42:37 kali sh[11040]: Aborted!
Sep 05 13:42:37 kali systemd[1]: python-faraday.service: Control process exited, code=exited status=1
Sep 05 13:42:37 kali systemd[1]: python-faraday.service: Failed with result 'exit-code'.
Sep 05 13:42:37 kali systemd[1]: Failed to start python-faraday Server.

root@kali:/usr/share/python-faraday# ./faraday-server.py
Traceback (most recent call last):
  File "./faraday-server.py", line 189, in <module>
    main()
  File "./faraday-server.py", line 107, in main
    check_postgresql()
  File "./faraday-server.py", line 93, in check_postgresql
    if not db.session.query(Workspace).count():
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 153, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/_collections.py", line 1001, in __call__
    return self.registry.setdefault(key, self.createfunc())
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 2950, in __call__
    return self.class_(**local_kw)
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 143, in __init__
    bind = options.pop('bind', None) or db.engine
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 877, in engine
    return self.get_engine()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 896, in get_engine
    return connector.get_engine()
  File "/usr/share/python-faraday/server/models.py", line 96, in get_engine
    rv = super(CustomEngineConnector, self).get_engine()
  File "/usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py", line 553, in get_engine
    info = make_url(uri)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 211, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 267, in _parse_rfc1738_args
    return URL(name, **components)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/url.py", line 60, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: 'localhost'

**Comment by llazzaro** [comment]
Can you show me the contents of "/lib/systemd/system/python-faraday.service", I think you are calling manage.py and this is not required.

There seems to be an error on your connection_string at the [database] section of the file ~/.faraday/config/server.ini.

Did you follow install steps at the wiki? you need to execute "python manage.py initdb" the first time to configure the database.

**Comment by lmcthbe** [comment]
Ran python manage.py initdb and Faraday Server has started. 

Lost couchDB as Kali removed it in the process but Faraday is up and running. 

Case can be closed. Thanks

**Comment by llazzaro** [comment]
You are welcome! We are happy that the issue was resolved! 
If couchdb files are still in your hardrive you can mount a docker instance (instructions on the wiki) and then you can execute:

`python manage.py import_from_couchdb`

**Comment by lmcthbe** [comment]
I spoke too fast I still have the same issue with v3

2018-09-05 14:01:53,539 - faraday - INFO [api.py:110 -      _setUpAPIServer() ]  XMLRPC API server configured on ('localhost', 9876)
There was an error while starting Faraday:
*** No ports available! ***
2018-09-05 14:01:53,551 - faraday - INFO [api.py:489 -                  log() ]  Closing Faraday...

**Comment by llazzaro** [comment]
Did you try to set this values on the user.xml?

```
 <api_con_info_host>localhost</api_con_info_host>
  <api_con_info_port>9876</api_con_info_port>
  <api_restful_con_info_port>9977</api_restful_con_info_port>
```

**Comment by lmcthbe** [comment]
yes and after it failed api_restful_con_info_port is set back to 65535 and debug does not give much

2018-09-05 14:07:59,946 - faraday - DEBUG [api.py:495 -               devlog() ]  Starting application...
2018-09-05 14:07:59,946 - faraday - DEBUG [api.py:495 -               devlog() ]  Setting up remote API's...
2018-09-05 14:07:59,947 - faraday - DEBUG [api.py:495 -               devlog() ]  starting XMLRPCServer with api_conn_info = ('localhost', 9876)
2018-09-05 14:07:59,947 - faraday - INFO [api.py:110 -      _setUpAPIServer() ]  XMLRPC API server configured on ('localhost', 9876)
2018-09-05 14:07:59,947 - faraday - DEBUG [api.py:495 -               devlog() ]  Starting model controller daemon...
2018-09-05 14:07:59,947 - faraday - DEBUG [api.py:495 -               devlog() ]  starting xmlrpc api server...
There was an error while starting Faraday:
*** No ports available! ***
2018-09-05 14:09:36,279 - faraday - INFO [api.py:489 -                  log() ]  Closing Faraday...
2018-09-05 14:09:36,280 - faraday - DEBUG [api.py:495 -               devlog() ]  stopping model controller thread...
2018-09-05 14:09:36,280 - faraday - DEBUG [api.py:495 -               devlog() ]  server stopping...
2018-09-05 14:09:36,280 - faraday - DEBUG [api.py:495 -               devlog() ]  called stop on xmlrpc server
2018-09-05 14:09:38,042 - faraday - DEBUG [api.py:495 -               devlog() ]  server forever stopped by flag
2018-09-05 14:09:38,042 - faraday - DEBUG [api.py:495 -               devlog() ]  serve_forever ended
2018-09-05 14:09:38,042 - faraday - DEBUG [api.py:495 -               devlog() ]  xmlrpc thread joined
2018-09-05 14:09:39,958 - faraday - DEBUG [api.py:495 -               devlog() ]  Waiting for controller threads to end...

**Comment by llazzaro** [comment]
Ok one last try, instead of localhost use 127.0.0.1:

```
 <api_con_info_host>127.0.0.1</api_con_info_host>
  <api_con_info_port>9876</api_con_info_port>
  <api_restful_con_info_port>9977</api_restful_con_info_port>
```

**Comment by lmcthbe** [comment]
It worked :-)

**Comment by lmcthbe** [comment]
Thanks for the help and BTW the new UI is really nice
